# Generated by Django 5.2.15 on 2026-07-01 18:26

import uuid

import django.db.models.deletion
from django.db import migrations, models

import onboarding.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('site_domain', models.CharField(max_length=253)),
                ('site_tagline', models.CharField(blank=True, max_length=255)),
                ('bio_short', models.TextField(blank=True)),
                ('bio_long', models.TextField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('newsletter_link', models.CharField(blank=True, max_length=2048)),
                ('social_twitter', models.URLField(blank=True, max_length=2048)),
                ('social_instagram', models.URLField(blank=True, max_length=2048)),
                ('social_facebook', models.URLField(blank=True, max_length=2048)),
                ('social_tiktok', models.URLField(blank=True, max_length=2048)),
                ('social_youtube', models.URLField(blank=True, max_length=2048)),
                ('social_goodreads', models.URLField(blank=True, max_length=2048)),
                ('headshot', models.FileField(blank=True, max_length=500, upload_to=onboarding.models.author_headshot_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'book_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onboarding_position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.FileField(max_length=500, upload_to=onboarding.models.book_cover_path)),
                ('description', models.TextField()),
                ('buy_links', models.JSONField(default=list)),
                ('book_number', models.PositiveIntegerField(blank=True, null=True)),
                ('perfect_for', models.TextField(blank=True)),
                ('enjoy_if', models.TextField(blank=True)),
                ('sample_chapter', models.FileField(blank=True, max_length=500, upload_to=onboarding.models.sample_chapter_path)),
                ('sample_chapter_original_name', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='onboarding.author')),
            ],
            options={
                'db_table': 'book',
                'ordering': ['onboarding_position'],
            },
        ),
        migrations.CreateModel(
            name='BookAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('icon', models.FileField(max_length=500, upload_to=onboarding.models.award_icon_path)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='onboarding.book')),
            ],
            options={
                'db_table': 'book_award',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='AuthorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.bookcategory')),
            ],
            options={
                'db_table': 'author_category',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='selected_categories',
            field=models.ManyToManyField(related_name='authors', through='onboarding.AuthorCategory', to='onboarding.bookcategory'),
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='onboarding.bookcategory')),
            ],
            options={
                'db_table': 'book_genre',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='onboarding.bookgenre'),
        ),
        migrations.CreateModel(
            name='AuthorGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.bookgenre')),
            ],
            options={
                'db_table': 'author_genre',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='selected_genres',
            field=models.ManyToManyField(related_name='authors', through='onboarding.AuthorGenre', to='onboarding.bookgenre'),
        ),
        migrations.CreateModel(
            name='BookSubgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subgenres', to='onboarding.bookgenre')),
            ],
            options={
                'db_table': 'book_subgenre',
                'ordering': ['genre__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='subgenre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='onboarding.booksubgenre'),
        ),
        migrations.CreateModel(
            name='AuthorSubgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.author')),
                ('subgenre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.booksubgenre')),
            ],
            options={
                'db_table': 'author_subgenre',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='selected_subgenres',
            field=models.ManyToManyField(related_name='authors', through='onboarding.AuthorSubgenre', to='onboarding.booksubgenre'),
        ),
        migrations.CreateModel(
            name='EditorialReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=255)),
                ('quotation', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_reviews', to='onboarding.book')),
            ],
            options={
                'db_table': 'book_editorial_review',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('person_name', models.CharField(max_length=255)),
                ('credentials', models.CharField(blank=True, max_length=255)),
                ('quotation', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='onboarding.book')),
            ],
            options={
                'db_table': 'book_endorsement',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ReviewExcerpt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('stars', models.PositiveSmallIntegerField()),
                ('photo', models.FileField(max_length=500, upload_to=onboarding.models.reviewer_photo_path)),
                ('person_name', models.CharField(max_length=255)),
                ('quotation', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_excerpts', to='onboarding.book')),
            ],
            options={
                'db_table': 'book_review_excerpt',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_books', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='onboarding.author')),
            ],
            options={
                'db_table': 'series',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='onboarding.series'),
        ),
        migrations.AddConstraint(
            model_name='authorcategory',
            constraint=models.UniqueConstraint(fields=('author', 'category'), name='unique_author_category'),
        ),
        migrations.AddConstraint(
            model_name='authorcategory',
            constraint=models.UniqueConstraint(fields=('author', 'position'), name='unique_author_category_position'),
        ),
        migrations.AddConstraint(
            model_name='bookgenre',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_genre_per_category'),
        ),
        migrations.AddConstraint(
            model_name='authorgenre',
            constraint=models.UniqueConstraint(fields=('author', 'genre'), name='unique_author_genre'),
        ),
        migrations.AddConstraint(
            model_name='authorgenre',
            constraint=models.UniqueConstraint(fields=('author', 'position'), name='unique_author_genre_position'),
        ),
        migrations.AddConstraint(
            model_name='booksubgenre',
            constraint=models.UniqueConstraint(fields=('genre', 'name'), name='unique_subgenre_per_genre'),
        ),
        migrations.AddConstraint(
            model_name='authorsubgenre',
            constraint=models.UniqueConstraint(fields=('author', 'subgenre'), name='unique_author_subgenre'),
        ),
        migrations.AddConstraint(
            model_name='authorsubgenre',
            constraint=models.UniqueConstraint(fields=('author', 'position'), name='unique_author_subgenre_position'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique_series_name_per_author'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('author', 'onboarding_position'), name='unique_book_onboarding_position_per_author'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('onboarding_position__gte', 1)), name='book_onboarding_position_gte_1'),
        ),
    ]
