# Generated by Django 5.2.15 on 2026-07-01 21:04

import uuid

import django.db.models.deletion
from django.db import migrations, models

import onboarding.models


def consolidate_reviews_and_positions(apps, schema_editor):
    EditorialReview = apps.get_model("onboarding", "EditorialReview")
    Endorsement = apps.get_model("onboarding", "Endorsement")
    ReviewExcerpt = apps.get_model("onboarding", "ReviewExcerpt")
    BookReview = apps.get_model("onboarding", "BookReview")
    BookAward = apps.get_model("onboarding", "BookAward")

    for review in EditorialReview.objects.all().iterator():
        BookReview.objects.create(
            book_id=review.book_id,
            display_position=review.position + 1,
            is_editorial=True,
            reviewer_name=review.source,
            quotation=review.quotation,
            original_review_url=review.url or None,
        )

    endorsement_counts = {}
    for review in Endorsement.objects.all().iterator():
        BookReview.objects.create(
            book_id=review.book_id,
            display_position=review.position + 1,
            is_editorial=False,
            reviewer_name=review.person_name,
            credentials=review.credentials or None,
            quotation=review.quotation,
        )
        endorsement_counts[review.book_id] = max(
            endorsement_counts.get(review.book_id, 0),
            review.position + 1,
        )

    for review in ReviewExcerpt.objects.all().iterator():
        BookReview.objects.create(
            book_id=review.book_id,
            display_position=(
                endorsement_counts.get(review.book_id, 0)
                + review.position
                + 1
            ),
            is_editorial=False,
            reviewer_name=review.person_name,
            quotation=review.quotation,
            photo_path=review.photo,
            stars=review.stars,
        )

    for award in BookAward.objects.all().iterator():
        award.position += 1
        award.save(update_fields=["position"])


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_seed_genre_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_position', models.PositiveIntegerField()),
                ('is_editorial', models.BooleanField(default=False)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('credentials', models.CharField(blank=True, max_length=255, null=True)),
                ('quotation', models.TextField()),
                ('original_review_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('photo_path', models.FileField(blank=True, max_length=500, null=True, upload_to=onboarding.models.reviewer_photo_path)),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='onboarding.book')),
            ],
            options={
                'db_table': 'book_review',
                'ordering': ['display_position'],
            },
        ),
        migrations.RunPython(
            consolidate_reviews_and_positions,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='editorialreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reviewexcerpt',
            name='book',
        ),
        migrations.AlterModelOptions(
            name='authorcategory',
            options={'ordering': ['display_position']},
        ),
        migrations.AlterModelOptions(
            name='authorgenre',
            options={'ordering': ['display_position']},
        ),
        migrations.AlterModelOptions(
            name='authorsubgenre',
            options={'ordering': ['display_position']},
        ),
        migrations.AlterModelOptions(
            name='bookaward',
            options={'ordering': ['display_position']},
        ),
        migrations.RemoveConstraint(
            model_name='authorcategory',
            name='unique_author_category_position',
        ),
        migrations.RemoveConstraint(
            model_name='authorgenre',
            name='unique_author_genre_position',
        ),
        migrations.RemoveConstraint(
            model_name='authorsubgenre',
            name='unique_author_subgenre_position',
        ),
        migrations.RenameField(
            model_name='authorcategory',
            old_name='position',
            new_name='display_position',
        ),
        migrations.RenameField(
            model_name='authorgenre',
            old_name='position',
            new_name='display_position',
        ),
        migrations.RenameField(
            model_name='authorsubgenre',
            old_name='position',
            new_name='display_position',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_number',
            new_name='number_in_series',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='sample_chapter_original_name',
            new_name='sample_chapter_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='sample_chapter',
            new_name='sample_chapter_path',
        ),
        migrations.RenameField(
            model_name='bookaward',
            old_name='position',
            new_name='display_position',
        ),
        migrations.RenameField(
            model_name='bookaward',
            old_name='icon',
            new_name='icon_path',
        ),
        migrations.AddField(
            model_name='series',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='subgenre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='onboarding.booksubgenre'),
        ),
        migrations.AddConstraint(
            model_name='authorcategory',
            constraint=models.UniqueConstraint(fields=('author', 'display_position'), name='unique_author_category_position'),
        ),
        migrations.AddConstraint(
            model_name='authorgenre',
            constraint=models.UniqueConstraint(fields=('author', 'display_position'), name='unique_author_genre_position'),
        ),
        migrations.AddConstraint(
            model_name='authorsubgenre',
            constraint=models.UniqueConstraint(fields=('author', 'display_position'), name='unique_author_subgenre_position'),
        ),
        migrations.AlterModelTable(
            name='bookcategory',
            table='genre_category',
        ),
        migrations.AlterModelTable(
            name='bookgenre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='booksubgenre',
            table='genre_subgenre',
        ),
        migrations.AlterModelTable(
            name='series',
            table='book_series',
        ),
        migrations.DeleteModel(
            name='EditorialReview',
        ),
        migrations.DeleteModel(
            name='Endorsement',
        ),
        migrations.DeleteModel(
            name='ReviewExcerpt',
        ),
    ]
