# Generated by Django 5.2.15 on 2026-07-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_bookreview_remove_editorialreview_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='is_starred_review',
            field=models.BooleanField(default=False),
        ),
    ]
