# Generated by Django 5.2.15 on 2026-07-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_add_starred_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='selected_template',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
